modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/cassiancc/Raspberry-Core/issues"
license = "MIT"

[[mods]]
modId = "raspberry"
version = "${mod_version}"
displayName = "Raspberry Core"
authors = "cassiancc, DavigJ"
credits = "Features textures by Derb, nöelle, and noodleman, ideas/textures from raspmary. Contains some code from MerchantPug and from the Oreganized mod under MIT License."
description = '''
A collection of compatibility blocks, minor features, and fixes designed for the Raspberry Flavoured modpack.
'''
logoFile = "logo.png"

[[dependencies.raspberry]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.raspberry]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.raspberry]]
modId = "farmersdelight"
mandatory = false
versionRange = "[1.19.2-1.2.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.raspberry]]
modId = "blueprint"
mandatory = false
versionRange = "[6.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.raspberry]]
modId = "supplementaries"
mandatory = false
versionRange = "[1.19.2-2.4.20,)"
ordering = "AFTER"
side = "BOTH"